---
- name: testing
  hosts: localhost

  tasks: 

   - name: Prints messages, 
     ansible.builtin.debug:
        msg:
        - "Running {{policy.name}} on {{ item }}"
     with_items: "{{ target_clusters }}"
