---
- name: testing
  hosts: localhost

  tasks: 

   - name: Prints messages, 
     ansible.builtin.debug:
        msg:
        - "Your Ansible Job is running"

   - name: Print all available facts
     ansible.builtin.debug:
       var: ansible_facts
